auto-emoji = true

[emoji-names]
smiley = "Smiley"
grimacing = "Grimacing"
grin = "Grin"
joy = "Joy"
smile = "Smile"
sweat_smile = "Sweat smile"
laughing = "Laughing"
innocent = "Innocent"
wink = "Wink"
blush = "Blush"
slight_smile = "Slight smile"
upside_down = "Upside down"
relaxed = "Relaxed"
yum = "Yum"
relieved = "Relieved"
heart_eyes = "Heart eyes"
kissing_heart = "Kissing heart"
kissing = "Kissing"
kissing_smiling_eyes = "Kissing smiling eyes"
kissing_closed_eyes = "Kissing closed eyes"
stuck_out_tongue_winking_eye = "Stuck out tongue winking eye"
stuck_out_tongue_closed_eyes = "Stuck out tongue closed eyes"
stuck_out_tongue = "Stuck out tongue"
money_mouth = "Money mouth"
sunglasses = "Sunglasses"
smirk = "Smirk"
no_mouth = "No mouth"
neutral_face = "Neutral face"
expressionless = "Expressionless"
unamused = "Unamused"
rolling_eyes = "Rolling eyes"
flushed = "Flushed"
disappointed = "Disappointed"
worried = "Worried"
angry = "Angry"
rage = "Rage"
pensive = "Pensive"
confused = "Confused"
slight_frown = "Slight frown"
frowning2 = "Frowning 2"

[emoji-phrases]
smiley = []
grimacing = ["grimacing"]
grin = []
joy = ["haha", "hhhh", "lmao", "ﻬﻬﻬ", "lmfao", "joy"]
smile = ["welcome", "wlc", "smile"]
sweat_smile = ["sorry", "sweat_smile"]
laughing = ["lol", "xd"]
innocent = ["trust me", "not me", "innocent"]
wink = []
blush = []
slight_smile = [":)"]
upside_down = ["why"]
relaxed = ["relaxed"]
yum = ["yum", "yummy", "delicious"]
relieved = []
heart_eyes = ["love", "<3"]
kissing_heart = []
kissing = []
kissing_smiling_eyes = []
kissing_closed_eyes = ["kiss you", "kissing_closed_eyes"]
stuck_out_tongue_winking_eye = []
stuck_out_tongue_closed_eyes = []
stuck_out_tongue = []
money_mouth = ["money_mouth", "money", "rich"]
sunglasses = ["cool", "sunglasses"]
smirk = ["smirk", "i am better", "i am pro", "better than you"]
no_mouth = ["oh no", "no_mouth"]
neutral_face = ["neutral_face", "not funny", "._."]
expressionless = ["bruh", "-_-", "expressionless"]
unamused = []
rolling_eyes = ["duh", "really", "rolling_eyes"]
flushed = ["wtf", "flushed"]
disappointed = ["disappointed"]
worried = ["worried"]
angry = []
rage = ["mad", "hate you", "rage", ">:("]
pensive = ["alone", "pensive"]
confused = ["confused"]
slight_frown = ["slight_frown", "sad", ":("]
frowning2 = []